# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1118, 993)
        self.add_name = QtWidgets.QLineEdit(Form)
        self.add_name.setGeometry(QtCore.QRect(270, 190, 241, 51))
        self.add_name.setObjectName("add_name")
        self.add_degree = QtWidgets.QLineEdit(Form)
        self.add_degree.setGeometry(QtCore.QRect(270, 250, 241, 51))
        self.add_degree.setObjectName("add_degree")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(10, 320, 261, 61))
        self.label_14.setStyleSheet("font: 81 14pt \"Rockwell Extra Bold\";\n"
"font: 75 18pt \"Microsoft New Tai Lue\";")
        self.label_14.setObjectName("label_14")
        self.add_price = QtWidgets.QLineEdit(Form)
        self.add_price.setGeometry(QtCore.QRect(270, 470, 241, 51))
        self.add_price.setObjectName("add_price")
        self.add_type = QtWidgets.QLineEdit(Form)
        self.add_type.setGeometry(QtCore.QRect(280, 320, 241, 51))
        self.add_type.setObjectName("add_type")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(20, 520, 271, 61))
        self.label_17.setStyleSheet("font: 81 14pt \"Rockwell Extra Bold\";\n"
"font: 75 18pt \"Microsoft New Tai Lue\";")
        self.label_17.setObjectName("label_17")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(20, 460, 271, 61))
        self.label_16.setStyleSheet("font: 81 14pt \"Rockwell Extra Bold\";\n"
"font: 75 18pt \"Microsoft New Tai Lue\";")
        self.label_16.setObjectName("label_16")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(20, 390, 271, 61))
        self.label_15.setStyleSheet("font: 81 14pt \"Rockwell Extra Bold\";\n"
"font: 75 18pt \"Microsoft New Tai Lue\";")
        self.label_15.setObjectName("label_15")
        self.add_volume = QtWidgets.QLineEdit(Form)
        self.add_volume.setGeometry(QtCore.QRect(270, 530, 241, 51))
        self.add_volume.setObjectName("add_volume")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(10, 250, 271, 61))
        self.label_13.setStyleSheet("font: 81 14pt \"Rockwell Extra Bold\";\n"
"font: 75 18pt \"Microsoft New Tai Lue\";")
        self.label_13.setObjectName("label_13")
        self.save_id = QtWidgets.QLineEdit(Form)
        self.save_id.setGeometry(QtCore.QRect(660, 290, 241, 51))
        self.save_id.setObjectName("save_id")
        self.add_descript = QtWidgets.QLineEdit(Form)
        self.add_descript.setGeometry(QtCore.QRect(270, 400, 241, 51))
        self.add_descript.setObjectName("add_descript")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(20, 120, 61, 61))
        self.label_6.setStyleSheet("font: 81 14pt \"Rockwell Extra Bold\";\n"
"font: 75 18pt \"Microsoft New Tai Lue\";")
        self.label_6.setObjectName("label_6")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(10, 180, 271, 61))
        self.label_12.setStyleSheet("font: 81 14pt \"Rockwell Extra Bold\";\n"
"font: 75 18pt \"Microsoft New Tai Lue\";")
        self.label_12.setObjectName("label_12")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 0, 541, 91))
        self.label.setStyleSheet("font: 81 24pt \"Rockwell Extra Bold\";\n"
"font: 75 24pt \"Microsoft New Tai Lue\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(570, -20, 541, 91))
        self.label_2.setStyleSheet("font: 81 24pt \"Rockwell Extra Bold\";\n"
"font: 75 24pt \"Microsoft New Tai Lue\";")
        self.label_2.setObjectName("label_2")
        self.add = QtWidgets.QPushButton(Form)
        self.add.setGeometry(QtCore.QRect(30, 800, 331, 71))
        self.add.setStyleSheet("font: 81 24pt \"Rockwell Extra Bold\";\n"
"font: 75 24pt \"Microsoft New Tai Lue\";")
        self.add.setObjectName("add")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(570, 490, 261, 61))
        self.label_18.setStyleSheet("font: 81 14pt \"Rockwell Extra Bold\";\n"
"font: 75 18pt \"Microsoft New Tai Lue\";")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(580, 690, 271, 61))
        self.label_19.setStyleSheet("font: 81 14pt \"Rockwell Extra Bold\";\n"
"font: 75 18pt \"Microsoft New Tai Lue\";")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(580, 630, 271, 61))
        self.label_20.setStyleSheet("font: 81 14pt \"Rockwell Extra Bold\";\n"
"font: 75 18pt \"Microsoft New Tai Lue\";")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(580, 560, 271, 61))
        self.label_21.setStyleSheet("font: 81 14pt \"Rockwell Extra Bold\";\n"
"font: 75 18pt \"Microsoft New Tai Lue\";")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(570, 420, 271, 61))
        self.label_22.setStyleSheet("font: 81 14pt \"Rockwell Extra Bold\";\n"
"font: 75 18pt \"Microsoft New Tai Lue\";")
        self.label_22.setObjectName("label_22")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(570, 280, 61, 61))
        self.label_7.setStyleSheet("font: 81 14pt \"Rockwell Extra Bold\";\n"
"font: 75 18pt \"Microsoft New Tai Lue\";")
        self.label_7.setObjectName("label_7")
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setGeometry(QtCore.QRect(570, 350, 271, 61))
        self.label_23.setStyleSheet("font: 81 14pt \"Rockwell Extra Bold\";\n"
"font: 75 18pt \"Microsoft New Tai Lue\";")
        self.label_23.setObjectName("label_23")
        self.atribute = QtWidgets.QComboBox(Form)
        self.atribute.setGeometry(QtCore.QRect(920, 100, 161, 51))
        self.atribute.setObjectName("atribute")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(650, 30, 531, 91))
        self.label_3.setStyleSheet("font: 81 12pt \"Rockwell Extra Bold\";\n"
"font: 75 12pt \"Microsoft New Tai Lue\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(560, 200, 351, 61))
        self.label_4.setStyleSheet("font: 81 14pt \"Rockwell Extra Bold\";")
        self.label_4.setObjectName("label_4")
        self.save_name = QtWidgets.QLineEdit(Form)
        self.save_name.setGeometry(QtCore.QRect(810, 360, 241, 51))
        self.save_name.setObjectName("save_name")
        self.save_degree = QtWidgets.QLineEdit(Form)
        self.save_degree.setGeometry(QtCore.QRect(820, 430, 241, 51))
        self.save_degree.setObjectName("save_degree")
        self.save_type = QtWidgets.QLineEdit(Form)
        self.save_type.setGeometry(QtCore.QRect(840, 500, 241, 51))
        self.save_type.setObjectName("save_type")
        self.save_descrpt = QtWidgets.QLineEdit(Form)
        self.save_descrpt.setGeometry(QtCore.QRect(820, 560, 241, 51))
        self.save_descrpt.setObjectName("save_descrpt")
        self.save_price = QtWidgets.QLineEdit(Form)
        self.save_price.setGeometry(QtCore.QRect(660, 630, 241, 51))
        self.save_price.setObjectName("save_price")
        self.save_volume = QtWidgets.QLineEdit(Form)
        self.save_volume.setGeometry(QtCore.QRect(820, 690, 241, 51))
        self.save_volume.setObjectName("save_volume")
        self.save = QtWidgets.QPushButton(Form)
        self.save.setGeometry(QtCore.QRect(580, 800, 481, 71))
        self.save.setStyleSheet("font: 81 24pt \"Rockwell Extra Bold\";\n"
"font: 75 24pt \"Microsoft New Tai Lue\";")
        self.save.setObjectName("save")
        self.add_id = QtWidgets.QLineEdit(Form)
        self.add_id.setGeometry(QtCore.QRect(90, 120, 241, 51))
        self.add_id.setObjectName("add_id")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 580, 461, 111))
        self.label_5.setStyleSheet("font: 81 24pt \"Rockwell Extra Bold\";\n"
"font: 75 24pt \"Microsoft New Tai Lue\";")
        self.label_5.setObjectName("label_5")
        self.format = QtWidgets.QLineEdit(Form)
        self.format.setGeometry(QtCore.QRect(20, 680, 311, 71))
        self.format.setObjectName("format")
        self.back = QtWidgets.QPushButton(Form)
        self.back.setGeometry(QtCore.QRect(0, 920, 531, 61))
        self.back.setStyleSheet("font: 81 24pt \"Rockwell Extra Bold\";\n"
"font: 75 24pt \"Microsoft New Tai Lue\";")
        self.back.setObjectName("back")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_14.setText(_translate("Form", " Молотый/в зернах"))
        self.label_17.setText(_translate("Form", "Объём упаковки"))
        self.label_16.setText(_translate("Form", "Цена"))
        self.label_15.setText(_translate("Form", "Описание вкуса"))
        self.label_13.setText(_translate("Form", "Степень обжарки"))
        self.label_6.setText(_translate("Form", "ID"))
        self.label_12.setText(_translate("Form", "Название сорта"))
        self.label.setText(_translate("Form", "Добавить новые данные"))
        self.label_2.setText(_translate("Form", "Изменить существующие"))
        self.add.setText(_translate("Form", "Добавить"))
        self.label_18.setText(_translate("Form", " Молотый/в зернах"))
        self.label_19.setText(_translate("Form", "Объём упаковки"))
        self.label_20.setText(_translate("Form", "Цена"))
        self.label_21.setText(_translate("Form", "Описание вкуса"))
        self.label_22.setText(_translate("Form", "Степень обжарки"))
        self.label_7.setText(_translate("Form", "ID"))
        self.label_23.setText(_translate("Form", "Название сорта"))
        self.label_3.setText(_translate("Form", "Выберете столбец, который вы хотите поменять"))
        self.label_4.setText(_translate("Form", "Введите параметры столбца"))
        self.save.setText(_translate("Form", "Сохранить в БД"))
        self.label_5.setText(_translate("Form", "Введённые данные"))
        self.back.setText(_translate("Form", "На прошлую страницу"))
